{
 "title": "Locations",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Location save",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(location_save_seconds_sum[5m])/irate(location_save_seconds_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "location_get_p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(location_get_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Location Yandex get",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(location_yandex_get_seconds_sum[5m])/irate(location_yandex_get_seconds_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}