version: '3.7'
networks:
  elk:
services:
  elasticsearch:
    build: elasticsearch/
    networks:
      - elk
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    build: logstash/
    networks:
      - elk
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    expose:
      - 9999
    ports:
      - "9999:9999"
    links:
      - elasticsearch

  kibana:
    build: kibana/
    container_name: kibana
    networks:
      - elk
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    expose:
      - 5601
    ports:
      - "5601:5601"
    links:
      - elasticsearch